---
- name: debug Info
  hosts: all
  tasks:
    - win_feature:
       name: Web-Server
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
