---
- name: debug Info
  hosts: all
  tasks:
    - name: install IIS
      win_feature:
        name: Web-Server
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    # - name: create User Bob
    #   win_user:
    #     name: bob
    #     password: B0bP4ssw0rd
    #     state: present
    #     groups:
    #       - Users

